// Generated by CoffeeScript 1.6.3
(function() {
  var fs, md5, readCacheFile, writeCacheFile, zlib;

  fs = require('fs');

  zlib = require('zlib');

  md5 = require('./md5');

  writeCacheFile = function(href, data) {
    return fs.writeFileSync("cache/" + (md5(href)), data);
  };

  readCacheFile = function(href) {
    return fs.readFileSync("cache/" + (md5(href)));
  };

  module.exports.isCache = function(href) {
    return fs.existsSync("cache/" + (md5(href)));
  };

  module.exports.cache = function(href, data, encoding) {
    switch (encoding) {
      case 'gzip':
        return writeCacheFile(href, data);
      case 'deflate':
        return zlib.inflate(data, function(e, result) {
          return zlib.gzip(result, function(e, result) {
            return writeCacheFile(href, result);
          });
        });
      case void 0:
        return zlib.gzip(data, function(e, result) {
          return writeCacheFile(href, result);
        });
    }
  };

  module.exports.getCache = function(href) {
    return readCacheFile(href);
  };

  module.exports["delete"] = function(href) {
    return fs.unlink;
  };

}).call(this);
