// Generated by CoffeeScript 1.6.3
(function() {
  var fs, gets;

  fs = require('fs');

  gets = {};

  module.exports.get = function(key) {
    if (gets['key'] == null) {
      gets['key'] = this.load("" + key + ".json");
      return gets['key'];
    }
    return gets['key'];
  };

  module.exports.load = function(fileName) {
    return JSON.parse(fs.readFileSync(fileName));
  };

  module.exports.save = function(fileName, json) {
    return fs.writeFileSync(fileName, JSON.stringify(json));
  };

  module.exports.request = function(req, res, urlObj) {
    var json, newHostName;
    if (urlObj.query != null) {
      newHostName = urlObj.query.split('=')[1];
      json = this.get('hostnames');
      if (-1 === json.indexOf(newHostName)) {
        json.push(newHostName);
        this.save('hostnames.json', json);
      }
    }
    return fs.createReadStream('index.html').pipe(res);
  };

}).call(this);
