// Generated by CoffeeScript 1.6.3
(function() {
  var handler, http, server, zlib;

  zlib = require('zlib');

  http = require('http');

  handler = require('./handler');

  server = http.createServer();

  server.listen(12100, '0.0.0.0');

  server.on('error', function(e) {
    console.error("http:server:e");
    return console.dir(e);
  });

  server.on('request', function(req, res) {
    return handler(req, res);
  });

}).call(this);
