// Generated by CoffeeScript 1.6.3
(function() {
  var cache, crypto;

  crypto = require('crypto');

  cache = {};

  module.exports = function(val) {
    var shasum;
    if (cache[val] != null) {
      return cache[val];
    }
    shasum = crypto.createHash('md5');
    shasum.update(val);
    cache[val] = shasum.digest('hex');
    return cache[val];
  };

}).call(this);
